name: kalman
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - python=3
  - scipy
  - ipython
  - ca-certificates
  - certifi
  - openssl
  - mne-base
  - datalad
  - jupyter
  - pytest
  - hypothesis
